/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/japanhouse/japanhouse.glb -t -r public 
*/

import * as THREE from 'three'
import React, { useRef,useLayoutEffect } from 'react'
import { useGLTF,useScroll  } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import gsap from 'gsap'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane016: THREE.Mesh
    Plane016_1: THREE.Mesh
    Plane016_2: THREE.Mesh
    Plane016_3: THREE.Mesh
    Plane016_4: THREE.Mesh
    Plane016_5: THREE.Mesh
    Plane016_6: THREE.Mesh
    Plane016_7: THREE.Mesh
    Plane016_8: THREE.Mesh
    Plane016_9: THREE.Mesh
    Plane016_10: THREE.Mesh
    Plane016_11: THREE.Mesh
    Plane016_12: THREE.Mesh
    Plane016_13: THREE.Mesh
    Plane016_14: THREE.Mesh
    Plane016_15: THREE.Mesh
    Plane016_16: THREE.Mesh
    Plane016_17: THREE.Mesh
    Plane016_18: THREE.Mesh
    Plane016_19: THREE.Mesh
    Plane016_20: THREE.Mesh
    Plane016_21: THREE.Mesh
    Plane016_22: THREE.Mesh
    Plane016_23: THREE.Mesh
    Plane016_24: THREE.Mesh
    Plane016_25: THREE.Mesh
    Plane016_26: THREE.Mesh
    Plane016_27: THREE.Mesh
    Plane016_28: THREE.Mesh
    Plane016_29: THREE.Mesh
    Plane016_30: THREE.Mesh
    Plane016_31: THREE.Mesh
    Plane016_32: THREE.Mesh
    Plane016_33: THREE.Mesh
    Plane016_34: THREE.Mesh
    Plane016_35: THREE.Mesh
    Plane016_36: THREE.Mesh
    Plane016_37: THREE.Mesh
    Plane016_38: THREE.Mesh
    Plane016_39: THREE.Mesh
    Plane016_40: THREE.Mesh
    Plane016_41: THREE.Mesh
    Plane016_42: THREE.Mesh
    Plane016_43: THREE.Mesh
    Plane016_44: THREE.Mesh
    Plane016_45: THREE.Mesh
    Plane016_46: THREE.Mesh
    Plane016_47: THREE.Mesh
    Plane016_48: THREE.Mesh
    Plane016_49: THREE.Mesh
    Plane016_50: THREE.Mesh
    Plane016_51: THREE.Mesh
    Plane016_52: THREE.Mesh
  }
  materials: {
    floor1: THREE.MeshStandardMaterial
    floor2: THREE.MeshStandardMaterial
    neongreen: THREE.MeshStandardMaterial
    neonblue1: THREE.MeshStandardMaterial
    neonblue2: THREE.MeshStandardMaterial
    vending1: THREE.MeshStandardMaterial
    ['white-1']: THREE.MeshStandardMaterial
    ['brown-1']: THREE.MeshStandardMaterial
    ['brown-3']: THREE.MeshStandardMaterial
    ['white-2']: THREE.MeshStandardMaterial
    ['gray-2']: THREE.MeshStandardMaterial
    window1: THREE.MeshStandardMaterial
    ['silver-1']: THREE.MeshStandardMaterial
    ['capet.1']: THREE.MeshStandardMaterial
    ['capet.2']: THREE.MeshStandardMaterial
    rooftop: THREE.MeshStandardMaterial
    ['gray-1']: THREE.MeshStandardMaterial
    pink1: THREE.MeshStandardMaterial
    pink2: THREE.MeshStandardMaterial
    treetrunk: THREE.MeshStandardMaterial
    grass1: THREE.MeshStandardMaterial
    ['brown-2']: THREE.MeshStandardMaterial
    ['black-1']: THREE.MeshStandardMaterial
    ['yellow-2']: THREE.MeshStandardMaterial
    ['neon-white-logo']: THREE.MeshStandardMaterial
    ['blue-2']: THREE.MeshStandardMaterial
    ['yellow-1']: THREE.MeshStandardMaterial
    ['black-3']: THREE.MeshStandardMaterial
    bldg2: THREE.MeshStandardMaterial
    ems3: THREE.MeshStandardMaterial
    ['ems-red-1']: THREE.MeshStandardMaterial
    ['green-1']: THREE.MeshStandardMaterial
    DOOR2: THREE.MeshStandardMaterial
    soil: THREE.MeshStandardMaterial
    ['neon-white']: THREE.MeshStandardMaterial
    ['neon-cyan']: THREE.MeshStandardMaterial
    ['neon-green']: THREE.MeshStandardMaterial
    ['neon-pink']: THREE.MeshStandardMaterial
    metal1: THREE.MeshStandardMaterial
    ['neongreen.001']: THREE.MeshStandardMaterial
    ['white-2.2']: THREE.MeshStandardMaterial
    blue1: THREE.MeshStandardMaterial
    AC1: THREE.MeshStandardMaterial
    pipe1: THREE.MeshStandardMaterial
    RED1: THREE.MeshStandardMaterial
    glass1: THREE.MeshStandardMaterial
    ['silver-1.001']: THREE.MeshStandardMaterial
    vending2: THREE.MeshStandardMaterial
    vending3: THREE.MeshStandardMaterial
    vending4: THREE.MeshStandardMaterial
    vending5: THREE.MeshStandardMaterial
    ['green-2']: THREE.MeshStandardMaterial
    grass2: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Japanhouse(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/japanhouse/japanhouse.glb') as GLTFResult
  const jpnhouse = useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 4, ease: 'power1.inOut'}})
    

    tl.current

    // <Japanhouse scale={0.4} position={[2, -2.8, 0]} rotation={[ 0, -2.5, 0]}/>

    .to(jpnhouse.current.position, {x: 2}, 0)
    .to(jpnhouse.current.position, {y: -2.5}, 0)
    .to(jpnhouse.current.position, {z: 0}, 0)
    .to(jpnhouse.current.rotation, {x: 0}, 0)
    .to(jpnhouse.current.rotation, {y: -1.8}, 0)
    .to(jpnhouse.current.rotation, {z: 0}, 0)
    .to(jpnhouse.current.scale, {x: 0.45}, 0)
    .to(jpnhouse.current.scale, {y: 0.45}, 0)
    .to(jpnhouse.current.scale, {z: 0.45}, 0)

    .to(jpnhouse.current.position, {x: 2}, 5)
    .to(jpnhouse.current.position, {y: -2}, 5)
    .to(jpnhouse.current.position, {z: 0}, 5)
    .to(jpnhouse.current.rotation, {x: 0}, 5)
    .to(jpnhouse.current.rotation, {y: -3.5}, 5)
    .to(jpnhouse.current.rotation, {z: 0}, 5)

    .to(jpnhouse.current.position, {x: 2}, 10)
    .to(jpnhouse.current.position, {y: -3}, 10)
    .to(jpnhouse.current.position, {z: 0}, 10)
    .to(jpnhouse.current.rotation, {x: 0}, 10)
    .to(jpnhouse.current.rotation, {y: -2}, 10)
    .to(jpnhouse.current.rotation, {z: 0}, 10)

  },[])
  return (
    <group {...props} dispose={null} ref={jpnhouse}>
      <pointLight intensity={0.05} decay={2} position={[2.603, 9.043, 1.846]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} position={[2.603, 7.835, 1.698]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} position={[2.603, 6.284, 2.021]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#ff0ff7" position={[2.603, 6.284, 1.321]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} position={[1.81, 8.004, 3.186]} scale={[0.202, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#ffbb00" position={[2.603, 6.284, 0.055]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={1} decay={2} color="#ffbb00" position={[1.473, 6.157, -2.076]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#ffbb00" position={[-1.716, 6.157, -3.081]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#ffbb00" position={[-2.206, 8.718, -2.819]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#ffbb00" position={[0.102, 8.718, -1.347]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#ffbb00" position={[0.933, 8.718, 0.197]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#66ff00" position={[0.102, 10.274, -1.78]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} position={[0.102, 10.711, -0.853]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} position={[-3.591, 6.803, -5.002]} scale={[0.205, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#45fe20" position={[-0.687, 5.967, -3.972]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#ffbb00" position={[-0.698, 5.411, -4.543]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} position={[0.331, 6.053, -2.715]} scale={[0.297, 0.227, 0.229]} />
      
      {/* Boosterlight  */}
      <pointLight intensity={1} decay={2} color="#00eeff" position={[3.466, 1.451, 2.136]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={1} decay={2} color="#00eeff" position={[3.231, 2.179, -2.723]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={1} decay={2} color="#00eeff" position={[-3.956, 2.035, -2.723]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={1} decay={2} color="#00eeff" position={[-4.21, 1.451, 2.136]} scale={[0.297, 0.227, 0.229]} />
      
      <pointLight intensity={0.05} decay={2} color="#fe2020" position={[-1.879, 0.559, 0.868]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#fe2020" position={[0.369, 0.559, -2.077]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#fe2020" position={[-1.859, 3.255, -4.589]} scale={[0.297, 0.227, 0.229]} />
      <spotLight intensity={0.05} angle={Math.PI / 10} penumbra={0.1} decay={2} color="#fb00ff" position={[-6.812, 15.951, -11.613]} />
      <pointLight intensity={0.05} decay={2} color="#27fb23" position={[2.603, 7.501, 2.033]} scale={[0.297, 0.227, 0.229]} />
      <pointLight intensity={0.05} decay={2} color="#00fbff" position={[2.603, 8.661, 1.846]} scale={[0.297, 0.227, 0.229]} />
      <spotLight intensity={0.05} angle={Math.PI / 10} penumbra={0.1} decay={2} color="#00ccff" position={[1.742, 15.951, 12.469]} />
      <group position={[-0.051, 4.099, -0.49]} scale={3.909}>
        <mesh geometry={nodes.Plane016.geometry} material={materials.floor1} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.floor2} />
        <mesh geometry={nodes.Plane016_2.geometry} material={materials.neongreen} />
        <mesh geometry={nodes.Plane016_3.geometry} material={materials.neonblue1} />
        <mesh geometry={nodes.Plane016_4.geometry} material={materials.neonblue2} />
        <mesh geometry={nodes.Plane016_5.geometry} material={materials.vending1} />
        <mesh geometry={nodes.Plane016_6.geometry} material={materials['white-1']} />
        <mesh geometry={nodes.Plane016_7.geometry} material={materials['brown-1']} />
        <mesh geometry={nodes.Plane016_8.geometry} material={materials['brown-3']} />
        <mesh geometry={nodes.Plane016_9.geometry} material={materials['white-2']} />
        <mesh geometry={nodes.Plane016_10.geometry} material={materials['gray-2']} />
        <mesh geometry={nodes.Plane016_11.geometry} material={materials.window1} />
        <mesh geometry={nodes.Plane016_12.geometry} material={materials['silver-1']} />
        <mesh geometry={nodes.Plane016_13.geometry} material={materials['capet.1']} />
        <mesh geometry={nodes.Plane016_14.geometry} material={materials['capet.2']} />
        <mesh geometry={nodes.Plane016_15.geometry} material={materials.rooftop} />
        <mesh geometry={nodes.Plane016_16.geometry} material={materials['gray-1']} />
        <mesh geometry={nodes.Plane016_17.geometry} material={materials.pink1} />
        <mesh geometry={nodes.Plane016_18.geometry} material={materials.pink2} />
        <mesh geometry={nodes.Plane016_19.geometry} material={materials.treetrunk} />
        <mesh geometry={nodes.Plane016_20.geometry} material={materials.grass1} />
        <mesh geometry={nodes.Plane016_21.geometry} material={materials['brown-2']} />
        <mesh geometry={nodes.Plane016_22.geometry} material={materials['black-1']} />
        <mesh geometry={nodes.Plane016_23.geometry} material={materials['yellow-2']} />
        <mesh geometry={nodes.Plane016_24.geometry} material={materials['neon-white-logo']} />
        <mesh geometry={nodes.Plane016_25.geometry} material={materials['blue-2']} />
        <mesh geometry={nodes.Plane016_26.geometry} material={materials['yellow-1']} />
        <mesh geometry={nodes.Plane016_27.geometry} material={materials['black-3']} />
        <mesh geometry={nodes.Plane016_28.geometry} material={materials.bldg2} />
        <mesh geometry={nodes.Plane016_29.geometry} material={materials.ems3} />
        <mesh geometry={nodes.Plane016_30.geometry} material={materials['ems-red-1']} />
        <mesh geometry={nodes.Plane016_31.geometry} material={materials['green-1']} />
        <mesh geometry={nodes.Plane016_32.geometry} material={materials.DOOR2} />
        <mesh geometry={nodes.Plane016_33.geometry} material={materials.soil} />
        <mesh geometry={nodes.Plane016_34.geometry} material={materials['neon-white']} />
        <mesh geometry={nodes.Plane016_35.geometry} material={materials['neon-cyan']} />
        <mesh geometry={nodes.Plane016_36.geometry} material={materials['neon-green']} />
        <mesh geometry={nodes.Plane016_37.geometry} material={materials['neon-pink']} />
        <mesh geometry={nodes.Plane016_38.geometry} material={materials.metal1} />
        <mesh geometry={nodes.Plane016_39.geometry} material={materials['neongreen.001']} />
        <mesh geometry={nodes.Plane016_40.geometry} material={materials['white-2.2']} />
        <mesh geometry={nodes.Plane016_41.geometry} material={materials.blue1} />
        <mesh geometry={nodes.Plane016_42.geometry} material={materials.AC1} />
        <mesh geometry={nodes.Plane016_43.geometry} material={materials.pipe1} />
        <mesh geometry={nodes.Plane016_44.geometry} material={materials.RED1} />
        <mesh geometry={nodes.Plane016_45.geometry} material={materials.glass1} />
        <mesh geometry={nodes.Plane016_46.geometry} material={materials['silver-1.001']} />
        <mesh geometry={nodes.Plane016_47.geometry} material={materials.vending2} />
        <mesh geometry={nodes.Plane016_48.geometry} material={materials.vending3} />
        <mesh geometry={nodes.Plane016_49.geometry} material={materials.vending4} />
        <mesh geometry={nodes.Plane016_50.geometry} material={materials.vending5} />
        <mesh geometry={nodes.Plane016_51.geometry} material={materials['green-2']} />
        <mesh geometry={nodes.Plane016_52.geometry} material={materials.grass2} />
      </group>
    </group>
  )
}

useGLTF.preload('/japanhouse/japanhouse.glb')
